config/routes.rb
Rails.application.routes.draw do
  resources :bundle_totals
  resources :bundles
  resources :line_items
  resources :products

  resources :orders do
    resources :line_items
  end

  root 'orders#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bundle.rb
class Bundle < ApplicationRecord

  belongs_to :product

  validates :bundle_quantity, presence: true, numericality: true
  validates :bundle_cost, presence: true, numericality: true

end

app/controllers/bundles_controller.rb
class BundlesController < ApplicationController
  before_action :set_bundle, only: [:show, :edit, :update, :destroy]

  # GET /bundles
  # GET /bundles.json
  def index
    @bundles = Bundle.all
  end

  # GET /bundles/1
  # GET /bundles/1.json
  def show
  end

  # GET /bundles/new
  def new
    @bundle = Bundle.new
  end

  # GET /bundles/1/edit
  def edit
  end

  # POST /bundles
  # POST /bundles.json
  def create
    @bundle = Bundle.new(bundle_params)

    respond_to do |format|
      if @bundle.save
        format.html { redirect_to @bundle, notice: 'Bundle was successfully created.' }
        format.json { render :show, status: :created, location: @bundle }
      else
        format.html { render :new }
        format.json { render json: @bundle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bundles/1
  # PATCH/PUT /bundles/1.json
  def update
    respond_to do |format|
      if @bundle.update(bundle_params)
        format.html { redirect_to @bundle, notice: 'Bundle was successfully updated.' }
        format.json { render :show, status: :ok, location: @bundle }
      else
        format.html { render :edit }
        format.json { render json: @bundle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bundles/1
  # DELETE /bundles/1.json
  def destroy
    @bundle.destroy
    respond_to do |format|
      format.html { redirect_to bundles_url, notice: 'Bundle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bundle
      @bundle = Bundle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bundle_params
      params.require(:bundle).permit(:bundle_quantity, :bundle_cost, :product_id)
    end
end

app/helpers/bundles_helper.rb
module BundlesHelper
end

app/views/bundles/_form.html.erb
<%= form_for(bundle) do |f| %>
  <% if bundle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bundle.errors.count, "error") %> prohibited this bundle from being saved:</h2>

      <ul>
      <% bundle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bundle_quantity %>
    <%= f.number_field :bundle_quantity %>
  </div>

  <div class="field">
    <%= f.label :bundle_cost %>
    <%= f.text_field :bundle_cost %>
  </div>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.text_field :product_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bundles/edit.html.erb
<h1>Editing Bundle</h1>

<%= render 'form', bundle: @bundle %>

<%= link_to 'Show', @bundle %> |
<%= link_to 'Back', bundles_path %>

app/views/bundles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bundles</h1>

<table>
  <thead>
    <tr>
      <th>Bundle quantity</th>
      <th>Bundle cost</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bundles.each do |bundle| %>
      <tr>
        <td><%= bundle.bundle_quantity %></td>
        <td><%= bundle.bundle_cost %></td>
        <td><%= bundle.product %></td>
        <td><%= link_to 'Show', bundle %></td>
        <td><%= link_to 'Edit', edit_bundle_path(bundle) %></td>
        <td><%= link_to 'Destroy', bundle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bundle', new_bundle_path %>

app/views/bundles/new.html.erb
<h1>New Bundle</h1>

<%= render 'form', bundle: @bundle %>

<%= link_to 'Back', bundles_path %>

app/views/bundles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bundle quantity:</strong>
  <%= @bundle.bundle_quantity %>
</p>

<p>
  <strong>Bundle cost:</strong>
  <%= @bundle.bundle_cost %>
</p>

<p>
  <strong>Product:</strong>
  <%= @bundle.product %>
</p>

<%= link_to 'Edit', edit_bundle_path(@bundle) %> |
<%= link_to 'Back', bundles_path %>