config/routes.rb
Rails.application.routes.draw do
  resources :bundle_totals
  resources :bundles
  resources :line_items
  resources :products

  resources :orders do
    resources :line_items
  end

  root 'orders#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bundle_total.rb
class BundleTotal < ApplicationRecord

  belongs_to :line_item

  validates :bundle_quantity, presence: true, numericality: true
  validates :bundle_size, presence: true, numericality: true
  validates :bundle_cost, presence: true, numericality: true

end

app/controllers/bundle_totals_controller.rb
class BundleTotalsController < ApplicationController
  before_action :set_bundle_total, only: [:show, :edit, :update, :destroy]

  # GET /bundle_totals
  # GET /bundle_totals.json
  def index
    @bundle_totals = BundleTotal.all
  end

  # GET /bundle_totals/1
  # GET /bundle_totals/1.json
  def show
  end

  # GET /bundle_totals/new
  def new
    @bundle_total = BundleTotal.new
  end

  # GET /bundle_totals/1/edit
  def edit
  end

  # POST /bundle_totals
  # POST /bundle_totals.json
  def create
    @bundle_total = BundleTotal.new(bundle_total_params)

    respond_to do |format|
      if @bundle_total.save
        format.html { redirect_to @bundle_total, notice: 'Bundle total was successfully created.' }
        format.json { render :show, status: :created, location: @bundle_total }
      else
        format.html { render :new }
        format.json { render json: @bundle_total.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bundle_totals/1
  # PATCH/PUT /bundle_totals/1.json
  def update
    respond_to do |format|
      if @bundle_total.update(bundle_total_params)
        format.html { redirect_to @bundle_total, notice: 'Bundle total was successfully updated.' }
        format.json { render :show, status: :ok, location: @bundle_total }
      else
        format.html { render :edit }
        format.json { render json: @bundle_total.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bundle_totals/1
  # DELETE /bundle_totals/1.json
  def destroy
    @bundle_total.destroy
    respond_to do |format|
      format.html { redirect_to bundle_totals_url, notice: 'Bundle total was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bundle_total
      @bundle_total = BundleTotal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bundle_total_params
      params.require(:bundle_total).permit(:bundle_quantity, :bundle_size, :bundle_cost, :line_item_id)
    end
end

app/helpers/bundle_totals_helper.rb
module BundleTotalsHelper
end

app/views/bundle_totals/_form.html.erb
<%= form_for(bundle_total) do |f| %>
  <% if bundle_total.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bundle_total.errors.count, "error") %> prohibited this bundle_total from being saved:</h2>

      <ul>
      <% bundle_total.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bundle_quantity %>
    <%= f.number_field :bundle_quantity %>
  </div>

  <div class="field">
    <%= f.label :bundle_size %>
    <%= f.number_field :bundle_size %>
  </div>

  <div class="field">
    <%= f.label :bundle_cost %>
    <%= f.text_field :bundle_cost %>
  </div>

  <div class="field">
    <%= f.label :line_item_id %>
    <%= f.text_field :line_item_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bundle_totals/edit.html.erb
<h1>Editing Bundle Total</h1>

<%= render 'form', bundle_total: @bundle_total %>

<%= link_to 'Show', @bundle_total %> |
<%= link_to 'Back', bundle_totals_path %>

app/views/bundle_totals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bundle Totals</h1>

<table>
  <thead>
    <tr>
      <th>Bundle quantity</th>
      <th>Bundle size</th>
      <th>Bundle cost</th>
      <th>Line item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bundle_totals.each do |bundle_total| %>
      <tr>
        <td><%= bundle_total.bundle_quantity %></td>
        <td><%= bundle_total.bundle_size %></td>
        <td><%= bundle_total.bundle_cost %></td>
        <td><%= bundle_total.line_item %></td>
        <td><%= link_to 'Show', bundle_total %></td>
        <td><%= link_to 'Edit', edit_bundle_total_path(bundle_total) %></td>
        <td><%= link_to 'Destroy', bundle_total, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bundle Total', new_bundle_total_path %>

app/views/bundle_totals/new.html.erb
<h1>New Bundle Total</h1>

<%= render 'form', bundle_total: @bundle_total %>

<%= link_to 'Back', bundle_totals_path %>

app/views/bundle_totals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bundle quantity:</strong>
  <%= @bundle_total.bundle_quantity %>
</p>

<p>
  <strong>Bundle size:</strong>
  <%= @bundle_total.bundle_size %>
</p>

<p>
  <strong>Bundle cost:</strong>
  <%= @bundle_total.bundle_cost %>
</p>

<p>
  <strong>Line item:</strong>
  <%= @bundle_total.line_item %>
</p>

<%= link_to 'Edit', edit_bundle_total_path(@bundle_total) %> |
<%= link_to 'Back', bundle_totals_path %>