config/routes.rb
Rails.application.routes.draw do
  resources :bundle_totals
  resources :bundles
  resources :line_items
  resources :products

  resources :orders do
    resources :line_items
  end

  root 'orders#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  has_many :bundle_totals

  validates :quantity, presence: true, numericality: true

  validate :allocate_bundle_totals

  def allocate_bundle_totals
    calculate_bundle_quantities.each do |quantity|
      bundle_totals << BundleTotal.new(bundle_quantity: quantity[0], bundle_size: quantity[1], bundle_cost: quantity[2])
    end
  end

  def item_total_cost
    bundle_totals.map{|f| [f.bundle_cost, f.bundle_quantity]}.inject(0){|memo, cost| memo + (cost[0] * cost[1])}
  end

  private

  def calculate_bundle_quantities
    bundle_quantities = []
    quantity = self.quantity

    sorted_bundles = product.bundles.map{|bundle| [bundle.bundle_quantity, bundle.bundle_cost]}.sort {|a,b| b[1] <=> a[1]}

    sorted_bundles.each do |bundle|
      num_bundles =  quantity / bundle[0]
      quantity = quantity % bundle[0]
      bundle_quantities << [num_bundles, bundle[0], bundle[1]] if num_bundles!=0
    end


    if check_valid_quantity?(bundle_quantities, self.quantity)
      bundle_quantities
    else
      string = sorted_bundles.map{|pack|pack[0]}.map {|a| a.to_s}.join(",")
      errors.add(:quantity, "must be divisible by the following pack sizes: #{string}")
    end

  end

  def check_valid_quantity?(bundle_quantities, quantity)
    calc_quantity = bundle_quantities.inject(0){|memo, bundle| memo + (bundle[0] * bundle[1])}
    calc_quantity == quantity ? true : false
  end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_item, only: [:destroy]
  before_filter :load_order

  def index
    @line_items = @order.line_items
    @order_total = @order.total_cost
  end

  def new
    @line_item = LineItem.new
  end

  def create
    @line_item = @order.line_items.new(line_item_params)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to order_line_items_url, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_line_item
    @line_item = LineItem.find(params[:id])
  end

  def load_order
    @order = Order.find(params[:order_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def line_item_params
    params.require(:line_item).permit(:order_id, :line_item_id, :product_id, :quantity)
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for([order, line_item], :html => { :role => "form" }) do |f| %>
    <% if line_item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line item from being saved:</h2>

          <ul>
            <% line_item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <table>
      <tr>
        <td>Product</td>
        <td>Quantity</td>
      </tr>
      <tr>
        <td><%= f.collection_select(:product_id, Product.order('name ASC'), :id, :name, {:prompt => 'Please select a Product'}) %></td>
        <td><%= f.number_field(:quantity, options ={value: 1, min: 1}) %></td>
      </tr>
    </table>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items for Order #<%= @line_items[0].order_id %></h1>

<table>
  <thead>
  <tr>
    <th style="text-align:left">Product</th>
    <th style="text-align:left">Code</th>
    <th style="text-align:left">Total Qty</th>
    <th style="text-align:left">Total Cost</th>
    <th style="text-align:left">No. of Packs</th>
    <th style="text-align:left">Qty per Pack</th>
    <th style="text-align:left">Cost per Pack</th>
  </tr>
  </thead>
  <tbody>
  <% @line_items.each do |item| %>
      <tr>
        <td style="width:130px"> <%= item.product.name %></td>
        <td style="width:130px"> <%= item.product.code %></td>
        <td style="width:130px"> <%= item.quantity %></td>
        <td style="width:130px"> <%= number_to_currency(item.item_total_cost) %></td>
        <tr></tr>
        <% item.bundle_totals.each do |total| %>
          <td style="width:130px"></td>
          <td style="width:130px"></td>
          <td style="width:130px"></td>
          <td style="width:130px"></td>
          <td style="width:130px"> <%= total.bundle_quantity %> </td>
          <td style="width:130px"> <%= total.bundle_size %> </td>
          <td style="width:130px"> <%= number_to_currency(total.bundle_cost) %> </td>
  <tr></tr>
        <% end %>
  <% end %>
  </tr>
  <tr>
    <td style="width:100px"> <h3>Order Total</h3> </td>
    <td style="width:100px"><h3><%= number_to_currency(@order_total) %></h3></td>
  </tr>
  </tbody>
</table>

<%= link_to 'Add Item', new_order_line_item_path(order_id: @order.id) %>
<br>
<%= link_to 'View all Orders', orders_path %>

app/views/line_items/new.html.erb
<h1>Add new line item</h1>

<%= render 'form', line_item: @line_item, order: @order %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @line_item.quantity %>
</p>

<p>
  <strong>Order:</strong>
  <%= @line_item.order %>
</p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>